<?php

namespace App\Controllers\API\v1;

use App\Models\UserModel;
use CodeIgniter\RESTful\ResourceController;
use Config\Database;

class Recipe extends ResourceController
{
    protected $db;
    protected $modelName = 'App\Models\RecipeModel';
    protected $format = 'json';

    public function __construct()
    {
        $this->db = Database::connect();
    }

    public function index()
	{
	    return $this->respond($this->model->findAll());
	}

	public function show($keyword = null)
    {
        if (is_numeric($keyword)) {
            $data = $this->model->find($keyword);
        } else {
            $builder = $this->db->table('recipe');
            $builder->like('name', htmlspecialchars($keyword));
            $data = $builder->get()->getCustomResultObject(\App\Entities\Recipe::class);
        }

        return $this->respond($data, $data !== null ? 200 : 404);
    }

    public function create()
    {
        $data = $this->request->getPost();
        $recipe = new \App\Entities\Recipe;
        $recipe->fill($data);
        $this->model->save($recipe);

        return $this->respond(200); // TODO: Change the autogenerated stub
    }

    public function respond($data = null, int $status = null, $message = '')
    {
        return parent::respond(['status' => $status, 'data' => $data], $status);
    }
}
